### ISSUE TITLE
Scratch 3 Extension Loader!

### ISSUE THREAD

**Issue by retronbv** [Mrcomputer1/ScratchXto3#2]
> If anyone knows how to load an extension into Scratch 3 without modding it please tell me or if anyone has a up to date fork of Scratch 3 on GHPages that allows loading an extension easily.

Well, https://sheeptester.github.io/scratch-gui/?url= `URL TO CODE`
works fine

**Comment by retronbv** [comment]
@Mrcomputer1  hallo

**Comment by Mrcomputer1** [comment]
Somehow I missed this issue 😛 - I will add the link to the readme file.
